services:
  db:
    image: mysql:8.0
    container_name: vete_db_container
    restart: always
    environment:
      MYSQL_DATABASE: veterinaria_db
      MYSQL_ROOT_PASSWORD: root_password_segura
      MYSQL_USER: vete_user
      MYSQL_PASSWORD: vete_password
    ports:
      - "3306:3306"
    volumes:
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vete_backend_container
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql+pymysql://vete_user:vete_password@db:3306/veterinaria_db?charset=utf8mb4
      - SECRET_KEY=clave
      - JWT_SECRET_KEY=clave
    volumes:
      - ./backend:/app
      - uploads_data:/app/uploads
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vete_frontend_container
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    volumes:
      - ./frontend:/app
      # Ignorar la carpeta node_modules local para usar la del contenedor
      - /app/node_modules
    depends_on:
      - backend

volumes:
  db_data:
  uploads_data: